version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
      build: .
      restart: always
      ports:
        - "5000:5000"
      depends_on:
        db:
          condition: service_healthy
      environment:
        FLASK_ENV: development
        MYSQL_ROOT_PASSWORD: example
        MYSQL_DATABASE: test_db
      volumes:
        - .:/app

volumes:
  db_data: